# Name of your application. Used to uniquely configure containers.
service: hojastore

# Name of the container image.
image: e-orosco/hojastore

# Deploy to these servers.
servers:
  web:
    hosts:
      - 192.168.0.10
 
# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  server: ghcr.io
  username: e-orosco

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
env:
  secret:
    - DATABASE_PASSWORD
    - RAILS_MASTER_KEY
  clear:
    RAILS_SERVE_STATIC_FILES: true
    POSTGRES_HOST: hojastore-db
    TZ: America/Lima

accessories:
  db:
    image: postgres:14
    host: 192.168.0.10
    env:
      clear:
        POSTGRES_USER: hojastore
        POSTGRES_DB: hojastore_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

builder:
  arch: arm64
  remote: ssh://root@192.168.0.10

asset_path: /rails/public/assets

volumes:
  - "storage_hojastore:/rails/storage/"

proxy:
  host: hojastore.softwarebajodemanda.com
  ssl: false
  app_port: 3000
